#!/usr/bin/env bash

## Wofi Powermenu

## Files
CONFIG="$HOME/.config/wofi/config"
STYLE="$HOME/.config/wofi/style.css"
COLORS="$HOME/.config/wofi/colors"

## Wofi Command
wofi_command="wofi --show dmenu \
			--conf ${CONFIG} --style ${STYLE} --color ${COLORS} \
			--width=960 --height=300 \
			--cache-file=/dev/null \
			--hide-scroll --no-actions \
			--define=matching=fuzzy"

uptime=$(uptime -p | sed -e 's/up //g')

## Entries
shutdown=" Shutdown"
reboot=" Restart"
lock=" Lock"
suspend=" Sleep"
logout="﫼 Logout"
screen_off="Screen Off"
uefi="Boot to UEFI firmware"

# Variable passed to wofi
open_menu () {
	options="$lock\n$suspend\n$logout\n$reboot\n$screen_off\n$shutdown\n$uefi"

	chosen="$(echo -e "$options" | $wofi_command --prompt "UP - $uptime")"
	case $chosen in
		$shutdown)
				systemctl poweroff
			;;
		$reboot)
				systemctl reboot
			;;
		$lock)
			~/.config/sway/scripts/lockscreen
			;;
		$suspend)
				~/.config/sway/scripts/lockscreen
				systemctl suspend
			;;
		$screen_off)
			~/.config/sway/scripts/screenoff
			;;
		$uefi)
				systemctl reboot --firmware-setup
			;;
		$logout)
				killall sway
			;;
	esac
}

if [[ ! `pidof wofi` ]]; then
	open_menu
else
	pkill wofi
fi
